version: '3'

services:

  dbadmin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./components/api/swagger/swagger.yml:/docs/swagger.yml:ro
    environment:
      - SWAGGER_JSON=/docs/swagger.yml