start:
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

startdev:
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

stop:
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.prod.yml down