openapi: 3.0.0

info:
  title: Data Collector API

servers:
  - url: 'http://localhost:3000'

tags:
- name: "Trades"
  description: "Trades executed"

paths:
  /trades/day/{day}:
    get:
      tags:
        - "Trades"
      summary: "Get all trades executed during a given day"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid status value"
  /trades/between/{openingDay}/{closingDay}:
    get:
      tags:
        - "Trades"
      summary: "Get all trades executed between two given days"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid status value"
